// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusicaAut_BauteViviana.Models
{
    [Table("Artist")]
    public partial class Artist
    {
        public Artist()
        {
            Albums = new HashSet<Album>();
        }

        [Key]
        public int ArtistId { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [MinLength(3, ErrorMessage = "El campo nombre ha de tener mínimo 3 caracteres")]
        [DisplayName("Nombre")]

        public string Name { get; set; }

        [InverseProperty("Artist")]
        public virtual ICollection<Album> Albums { get; set; }
    }
}